export enum GroupCoverType {
  file = 'file',
  noCover = 'noCover',
  unknown = 'unknown',
  cover1 = 'cover1',
  cover2 = 'cover2',
  cover3 = 'cover3',
  cover4 = 'cover4',
  cover5 = 'cover5',
  cover6 = 'cover6',
  cover7 = 'cover7',
  cover8 = 'cover8',
  cover9 = 'cover9',
  cover10 = 'cover10',
  cover11 = 'cover11',
  cover12 = 'cover12',
  cover13 = 'cover13',
  cover14 = 'cover14',
}
